# Generated by Django 4.2.13 on 2024-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.TextField()),
                ('course_description', models.TextField()),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('code', models.PositiveSmallIntegerField()),
                ('grading_system', models.CharField(max_length=20)),
                ('course_materials', models.TextField()),
            ],
        ),
    ]
