# Generated by Django 4.2.13 on 2024-06-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('class_capacity', models.PositiveIntegerField()),
                ('class_attendance', models.TextField()),
                ('class_projects', models.TextField()),
                ('class_activities', models.TextField()),
                ('class_representatives', models.TextField()),
                ('class_assignments', models.TextField()),
                ('class_policies', models.TextField()),
                ('class_requirements', models.TextField()),
            ],
        ),
    ]
